<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "errbit"
 *
 * Auto generated by Extension Builder 2017-02-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Errbit for Typo3',
    'description' => 'Integrates errbit error catcher for typo3',
    'category' => 'services',
    'author' => 'Eike  Starkmann',
    'author_email' => 'eike.starkmann@posteo.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.2',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.6.0-8.7.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
    'autoload' =>
        array(
            'psr-4' => array('Eike\\Errbit\\' => 'Classes')
        ),
);
